# spring.application.name : Application Name ?? (front-end? ??)
# spring.datasource : ?? DB ??
# spring.datasource.hikari.maximum-pool-size = 4 : DataBase Connection Pool ??
# spring.mvc.hiddenmethod.filter.enabled : MVC ????? Hidden Method ?? ?? ?? (Form ? ?? PUT, DELETE ????? ? ? ???)
spring:
  application:
    name: webclient
  datasource:
    url: jdbc:mysql://34.125.199.220:3306/jh?characterEncoding=UTF-8
    username: datasolution
    password: 12
    driver-class-name: com.mysql.cj.jdbc.Driver

# server.port : 8082 ?? ??
# server.servlet.encoding : Embedded Tomcat? ??? ??
# server.shutdown
#  : Spring Boot 2.3 ?? ???? ???? ??
#  : ????? ??? ? ??? ????? ?? ??? 30?. ?? ???? ??? spring.lifecycle.timeout-per-shutdown-phase=1m ?? ?? ??
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful
